# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legend', models.CharField(max_length=32)),
                ('text_origin', models.TextField()),
                ('rot', models.PositiveSmallIntegerField(default=0)),
                ('encrypt', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
